version: "3"
services:
  api:
    build: ./api
    volumes:
      - .:/code/api
    ports:
      - "80:80"
  web:
    build: ./web
    volumes:
      - .:/code/web
    ports:
      - "3000:3000"
    depends_on:
      - api
